# llm_pr_automation.py

"""
LLM PR Automation Tool
-----------------------
This script automatically:
- Detects LLM-generated test files
- Creates a Git branch (UT-gen-<timestamp>)
- Generates a PR title and description using LLM (OpenAI API)
- Pushes the branch
- Raises a Pull Request using GitHub API

Goal: Eliminate manual ZIP-based workflow for projects like Go UI testing.
"""

import os
import sys
import subprocess
import requests
import datetime
import argparse
import openai

# ----------- ARGUMENT PARSING -----------
def parse_args():
    parser = argparse.ArgumentParser(description="Automate PR creation for LLM-generated tests.")
    parser.add_argument("--repo", required=True, help="GitHub repository URL (e.g., https://github.com/user/repo)")
    parser.add_argument("--token", required=True, help="GitHub personal access token")
    parser.add_argument("--base-branch", default="main", help="Base branch for the pull request")
    parser.add_argument("--module", required=True, help="Language module name (e.g., Go UI module)")
    parser.add_argument("--framework", required=True, help="Framework name (e.g., Gin)")
    parser.add_argument("--author", required=True, help="Author name")
    parser.add_argument("--openai-api-key", required=True, help="OpenAI API key")
    return parser.parse_args()

# ----------- UTILITIES -----------
def run_command(cmd):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error running command: {cmd}\n{result.stderr}")
        sys.exit(1)
    return result.stdout.strip()

def create_branch(branch_name):
    run_command(f"git checkout -b {branch_name}")

def commit_tests(language_module, framework_name):
    run_command("git add tests/ || true")
    run_command(f"git commit -m 'Add LLM-generated unit tests for {language_module} using {framework_name}'")

def push_branch(branch_name):
    run_command(f"git push origin {branch_name}")

# ----------- LLM CALL FOR PR TITLE + DESC -----------
def generate_pr_title_desc(language_module, framework_name, timestamp, author_name, openai_api_key):
    openai.api_key = openai_api_key
    prompt = (
        f"Generate a concise and informative GitHub Pull Request title and description for the following context:\n"
        f"Language Module: {language_module}\n"
        f"Framework: {framework_name}\n"
        f"Timestamp: {timestamp}\n"
        f"Author: {author_name}\n"
        f"These are unit tests automatically generated by an LLM based on recent code changes."
    )

    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        content = response['choices'][0]['message']['content'].strip()
        lines = content.split("\n", 1)
        title = lines[0].strip()
        description = lines[1].strip() if len(lines) > 1 else ""
        return title, description
    except Exception as e:
        print(f"Failed to call OpenAI API: {e}")
        sys.exit(1)

# ----------- GITHUB API TO CREATE PR -----------
def create_pull_request(owner, repo_name, token, base_branch, head_branch, title, body):
    url = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    payload = {
        "title": title,
        "head": head_branch,
        "base": base_branch,
        "body": body
    }
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 201:
        print(f"Pull request created: {response.json()['html_url']}")
    else:
        print(f"Failed to create PR: {response.status_code} {response.text}")
        sys.exit(1)

# ----------- MAIN FLOW -----------
if __name__ == "__main__":
    args = parse_args()

    github_repo_url = args.repo
    github_token = args.token
    base_branch = args.base_branch
    language_module = args.module
    framework_name = args.framework
    author_name = args.author
    openai_api_key = args.openai_api_key

    repo_name = github_repo_url.rstrip("/").split("/")[-1]
    owner = github_repo_url.rstrip("/").split("/")[-2]
    timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"UT-gen-{timestamp}"

    print("Starting PR creation for LLM-generated unit tests...")
    create_branch(branch_name)
    commit_tests(language_module, framework_name)
    push_branch(branch_name)
    pr_title, pr_desc = generate_pr_title_desc(language_module, framework_name, timestamp, author_name, openai_api_key)
    create_pull_request(owner, repo_name, github_token, base_branch, branch_name, pr_title, pr_desc)
